In [81]:
import numpy as np
import pandas as pd
import seaborn as sns

In [82]:
data = pd.read_csv(r"M:\DATA ANALYST\INTERNSHIP ASSIGNMENT 1\Nassau Candy Distributor.csv")      # Reading CSV file

In [83]:
data.head()           # Checking Data

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

1. Row ID - Unique Row Identifier
2. Order ID - Unique Order Identifier
3. Order Date - Date of order
4. Ship Date - Date of shipment
5. Ship Mode - Shipping method of order
6. Customer ID	 - Unique customer identifier
7. Country/Region - Country or region of customer
8. City - City of customer
9. State/Province - State/province of customer
10. Postal Code - Postal code / zip code of customer
11. Division - Product division
12. Region - Region of customer
13. Product ID - Unique product identifier
14. Product Name - Product long namer
15. Sales - Total sales value of order
16. Units -	Total units of order
17. Gross Profit - Gross profit of order ( Sales - Cost )
18. Cost -	Cost to manufacture

In [84]:
data.info()         # 10194 rows, 18 columns.

<class 'pandas.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  str
 2   Order Date      10194 non-null  str
 3   Ship Date       10194 non-null  str
 4   Ship Mode       10194 non-null  str
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  str
 7   City            10194 non-null  str
 8   State/Province  10194 non-null  str
 9   Postal Code     10194 non-null  str
 10  Division        10194 non-null  str
 11  Region          10194 non-null  str
 12  Product ID      10194 non-null  str
 13  Product Name    10194 non-null  str
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), str(12)
memory usage: 1.4 MB

In [85]:
data = data[(data['Sales']>=0) & (data['Units']>=0) & (data['Cost']>=0) & (data['Gross Profit']>=0)]                   # Checking Sales, Units and Cost are Valid.

In [86]:
data.shape                        # All data is valid as 10194 rows and 18 columns.

(10194, 18)

We do not need to remove any row as the data is valid.

# CREATING KPI's

GROSS MARGIN % = Gross Profit/Sales

In [87]:
data['Gross Margin %'] = ((data['Gross Profit'])/(data['Sales'])*100).round(2)           # creating column named Gross Margin %

In [88]:
data.head()  # checking updated table.

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Gross Margin %
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,64.92
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,65.33
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,71.35
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,69.44
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,65.33

Profit Per Unit = Gross Profit/ Units

In [89]:
data['Profit Per Unit'] = data['Gross Profit']/data['Units']            # creating column named Profit Per Unit

In [90]:
data.head()  # Checking updated table

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost,Gross Margin %,Profit Per Unit
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28,64.92,2.11
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60,65.33,2.45
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00,71.35,2.49
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30,69.44,2.50
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90,65.33,2.45

Revenue Contribution = Product Sales/ Total Sales

In [91]:
data['Product Name'].unique()             # There are 15 unique products.

<StringArray>
[       'Wonka Bar - Milk Chocolate', 'Wonka Bar - Triple Dazzle Caramel',
 'Wonka Bar - Nutty Crunch Surprise',    'Wonka Bar -Scrumdiddlyumptious',
         'Wonka Bar - Fudge Mallows',                         'Wonka Gum',
                         'Kazookles',                'Lickable Wallpaper',
              'Fizzy Lifting Drinks',                       'Laffy Taffy',
                         'SweeTARTS',                             'Nerds',
                       'Hair Toffee',            'Everlasting Gobstopper',
                           'Fun Dip']
Length: 15, dtype: str

In [92]:
Contribution = data.groupby('Product Name')['Sales'].sum().reset_index()         # Making a new Data Frame for Revenue Contribution

In [93]:
Contribution.head(15)

                         Product Name     Sales
0              Everlasting Gobstopper    130.00
1                Fizzy Lifting Drinks     78.75
2                             Fun Dip     12.00
3                         Hair Toffee     76.50
4                           Kazookles   1205.75
5                         Laffy Taffy     53.73
6                  Lickable Wallpaper   7860.00
7                               Nerds     15.00
8                           SweeTARTS     61.50
9           Wonka Bar - Fudge Mallows  24890.40
10         Wonka Bar - Milk Chocolate  26867.75
11  Wonka Bar - Nutty Crunch Surprise  23574.95
12  Wonka Bar - Triple Dazzle Caramel  28485.00
13     Wonka Bar -Scrumdiddlyumptious  27874.80
14                          Wonka Gum    597.50

In [ ]:
Contribution['Number of Orders'] = data.groupby('Product Name')['Order ID'].count().values # creating no of orders of each candy type

In [95]:
Contribution.head(15)

                         Product Name     Sales  Number of Orders
0              Everlasting Gobstopper    130.00                 3
1                Fizzy Lifting Drinks     78.75                 6
2                             Fun Dip     12.00                 3
3                         Hair Toffee     76.50                 4
4                           Kazookles   1205.75                96
5                         Laffy Taffy     53.73                10
6                  Lickable Wallpaper   7860.00                94
7                               Nerds     15.00                 4
8                           SweeTARTS     61.50                10
9           Wonka Bar - Fudge Mallows  24890.40              1818
10         Wonka Bar - Milk Chocolate  26867.75              2137
11  Wonka Bar - Nutty Crunch Surprise  23574.95              1810
12  Wonka Bar - Triple Dazzle Caramel  28485.00              2015
13     Wonka Bar -Scrumdiddlyumptious  27874.80              2064
14                          Wonka Gum    597.50               120

In [96]:
Total_Sales = data['Sales'].sum()           # Calculating Total Sales

In [97]:
print(Total_Sales)

141783.63

In [98]:
Contribution['% Revenue Contribution'] = ((Contribution['Sales']/Total_Sales)*100).round(3)

In [99]:
Contribution.head(15)

,Product Name,Sales,Number of Orders,% Revenue Contribution
0,Everlasting Gobstopper,130.00,3,0.092
1,Fizzy Lifting Drinks,78.75,6,0.056
2,Fun Dip,12.00,3,0.008
3,Hair Toffee,76.50,4,0.054
4,Kazookles,1205.75,96,0.850
5,Laffy Taffy,53.73,10,0.038
6,Lickable Wallpaper,7860.00,94,5.544
7,Nerds,15.00,4,0.011
8,SweeTARTS,61.50,10,0.043
9,Wonka Bar - Fudge Mallows,24890.40,1818,17.555
10,Wonka Bar - Milk Chocolate,26867.75,2137,18.950
11,Wonka Bar - Nutty Crunch Surprise,23574.95,1810,16.627
12,Wonka Bar - Triple Dazzle Caramel,28485.00,2015,20.090
13,Wonka Bar -Scrumdiddlyumptious,27874.80,2064,19.660
14,Wonka Gum,597.50,120,0.421

Profit Contribution = Product Profit/ Total Profit

In [100]:
Contribution['Profit'] = data.groupby('Product Name')['Gross Profit'].sum().values

In [101]:
Contribution.head(15)

,Product Name,Sales,Number of Orders,% Revenue Contribution,Profit
0,Everlasting Gobstopper,130.00,3,0.092,104.00
1,Fizzy Lifting Drinks,78.75,6,0.056,47.25
2,Fun Dip,12.00,3,0.008,4.80
3,Hair Toffee,76.50,4,0.054,59.50
4,Kazookles,1205.75,96,0.850,92.75
5,Laffy Taffy,53.73,10,0.038,33.48
6,Lickable Wallpaper,7860.00,94,5.544,3930.00
7,Nerds,15.00,4,0.011,7.00
8,SweeTARTS,61.50,10,0.043,28.70
9,Wonka Bar - Fudge Mallows,24890.40,1818,17.555,16593.60
10,Wonka Bar - Milk Chocolate,26867.75,2137,18.950,17443.37
11,Wonka Bar - Nutty Crunch Surprise,23574.95,1810,16.627,16819.95
12,Wonka Bar - Triple Dazzle Caramel,28485.00,2015,20.090,18610.20
13,Wonka Bar -Scrumdiddlyumptious,27874.80,2064,19.660,19357.50
14,Wonka Gum,597.50,120,0.421,310.70

In [103]:
Total_Profit = data['Gross Profit'].sum().round(2)
print(Total_Profit)

93442.8

In [108]:
Contribution['% Profit Contribution'] = ((Contribution['Profit']/Total_Profit)*100).round(3)  # creating new column

In [109]:
Contribution.head(15)

,Product Name,Sales,Number of Orders,% Revenue Contribution,Profit,% Profit Contribution
0,Everlasting Gobstopper,130.00,3,0.092,104.00,0.111
1,Fizzy Lifting Drinks,78.75,6,0.056,47.25,0.051
2,Fun Dip,12.00,3,0.008,4.80,0.005
3,Hair Toffee,76.50,4,0.054,59.50,0.064
4,Kazookles,1205.75,96,0.850,92.75,0.099
5,Laffy Taffy,53.73,10,0.038,33.48,0.036
6,Lickable Wallpaper,7860.00,94,5.544,3930.00,4.206
7,Nerds,15.00,4,0.011,7.00,0.007
8,SweeTARTS,61.50,10,0.043,28.70,0.031
9,Wonka Bar - Fudge Mallows,24890.40,1818,17.555,16593.60,17.758
10,Wonka Bar - Milk Chocolate,26867.75,2137,18.950,17443.37,18.667
11,Wonka Bar - Nutty Crunch Surprise,23574.95,1810,16.627,16819.95,18.000
12,Wonka Bar - Triple Dazzle Caramel,28485.00,2015,20.090,18610.20,19.916
13,Wonka Bar -Scrumdiddlyumptious,27874.80,2064,19.660,19357.50,20.716
14,Wonka Gum,597.50,120,0.421,310.70,0.333